services:
  database:
    container_name: case_nexforce_database 
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /usr/docker/postgresql/ecommerce/:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
